name: learn_pro
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0-nullsafety.0
  http: ^0.13.3
  font_awesome_flutter: ^9.0.0
  fluttertoast: ^8.0.7
  custom_radio: ^0.1.2
  flutter_rating_bar: ^4.0.0
  page_transition: ^2.0.2
  flutter_spinkit: ^5.0.0
  shared_preferences: ^2.0.6
  provider: ^5.0.0
  bubble_bottom_bar: ^1.2.0
  flutter_slidable: ^0.6.0
  chewie: ^1.0.0
  video_player: ^2.0.2
  custom_switch: 
  bottom_navy_bar: ^6.0.0
  image_picker: ^0.8.4+11
  parse_server_sdk_flutter: ^3.1.0
  latlong2: ^0.8.0
  flutter_map:
  geocoder: 
  location: ^4.3.0
  positioned_tap_detector: ^1.0.3
  google_sign_in:
  firebase_auth: 
  firebase_core: 
  cloud_firestore:
  firebase_storage: ^10.0.3
  file_picker: ^4.0.3
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

module:
  androidX: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
   - assets/icon.png
   - assets/logo.png
   - assets/user_profile/
   - assets/new_course/
   - assets/json/
   - assets/video/
   - assets/payment_icon/
   - assets/onboarding/
   - assets/category/
   - assets/defaultuserimage.png
   - assets/123logo.png

  fonts:
    - family: Signika Negative
      fonts:
        - asset: fonts/signika_negative/SignikaNegative-Regular.ttf
        - asset: fonts/signika_negative/SignikaNegative-Bold.ttf
          weight: 700